TicketTrader/Models/TransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace TicketTrader.Models
{
    public class TransactionViewModel
    {
        public TransactionViewModel()
        {
        }

        public TransactionViewModel(List<Listing> listings)
        {
            this.Listings = listings;
            var firstListing = listings.FirstOrDefault();
            if (firstListing != null)
            {
                this.Event = firstListing.Event;
            }
        }

        public List<int> ListingIds { get; set; }
        public int EventId { get; set; }

        public string BandName { get; set; }
        public DateTime EventDate { get; set; }
        public string EventVenue { get; set; }


        public List<Listing> Listings { get; set; }
        public Event Event { get; set; }

        public int ListingId { get; set; }
        public string SellerId { get; set; }
        public string UserId { get; set; }
    }
}

TicketTrader/Controllers/BandController.cs
using System.Web.Mvc; 
using TicketTrader.Models;  
using TicketTrader.Data.Access; 

namespace TicketTrader.Controllers
{
    [Authorize(Roles="Admin")]
    public class BandController : Controller 
    {
        private TicketTraderContext db = new TicketTraderContext();
        
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(string searchTerm)
        {
            var bandDao = new BandDao(db);

            logger.Debug("Entered Band Index");
            return View(bandDao.GetAll(searchTerm));
        }

       
        [HttpGet]
        public ActionResult Create()
        { 
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Band band)
        {
            if (ModelState.IsValid)
            {
                var bandDao = new BandDao(db);
                bandDao.Add(band);
                logger.Debug("Created band--" + band.Name);
                return RedirectToAction("Index");
            }

            return View(band);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var bandDao = new BandDao(db);
            Band band = bandDao.GetById(id);
            if (band == null)
            {
                return HttpNotFound();
            }
            return View(band);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Band band)
        {
            if (ModelState.IsValid)
            {
                var bandDao = new BandDao(db);
                bandDao.Edit(band);
                logger.Debug("Edited Band--" + band.Name);
                return RedirectToAction("Index");
            }
            return View(band);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var bandDao = new BandDao(db);
            Band band = bandDao.GetById(id);
            if (band == null)
            {
                return HttpNotFound();
            }
            return View(band);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var bandDao = new BandDao(db);
            var band = bandDao.GetById(id);
            bandDao.Delete(band);
            logger.Debug("Deleted band--" + band.Name);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TicketTrader/Controllers/TransactionController.cs
using System.Linq;
using System.Web.Mvc;
using TicketTrader.Models;
using TicketTrader.Data.Access;
using Microsoft.AspNet.Identity;

namespace TicketTrader.Controllers
{
    public class TransactionController : Controller
    {
        private TicketTraderContext db = new TicketTraderContext();

        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Purchase(int id)
        {
            var listingDao = new ListingDao(db);

            var selectedListing = listingDao.GetById(id);

            var model = new TransactionViewModel(selectedListing);

            var totalPrice = model.Listing.Quantity * model.Listing.Price;
            model.Listing.Price = totalPrice;

            logger.Debug("Transaction Purchase Entered");
            return View(model);
        }

   
        [HttpPost]
        public ActionResult Purchase(TransactionViewModel viewModel)
        {
            var buyer = User.Identity.GetUserId();
            var seller = viewModel.SellerId;
            var listing = viewModel.ListingId;

            var transactionDao = new TransactionDao(db);
            transactionDao.SubmitPurchase(seller, buyer, listing);

            logger.Debug("Listing " + listing + " purchased");

            return RedirectToAction("Success", "Transaction");
        }

        [HttpGet]
        public ActionResult Success()
        {
            logger.Debug("Transaction Success Entered");
            return View();
        }
	}
}

TicketTrader/Views/Transaction/Purchase.cshtml
@model TicketTrader.Models.TransactionViewModel
@using Microsoft.AspNet.Identity;


@{
    ViewBag.Title = "Purchase";
}



<div id="purchaseInfo" class="panel panel-info pull-left">
    <div class="panel-heading">@Model.Event.Band.Name</div>


    <ul class="list-group">
        <li class="list-group-item">@Model.Event.Date</li>
        <li class="list-group-item">@Model.Event.Venue</li>
        <li class="list-group-item">$@Model.Listing.Price</li>
    </ul>
</div>


<div class="demo-container">
    <div class="card-wrapper"></div>

    <div class="form-container active">
        <form action="@Url.Action("Purchase", "Transaction")" class="purchaseForm" method="post">
            <div id="ccInput">
                <input placeholder="Card number" type="text" name="number" class="number">
                <input placeholder="Full name" type="text" name="name" class="name">
                <input placeholder="MM/YY" type="text" name="expiry" class="expiry">
                <input placeholder="CVC" type="text" name="cvc" class="cvc">
                <input type="hidden" value="@Model.Listing.ListingId" name="ListingId"/>
                <input type="hidden" value="@Model.Listing.UserId" name="SellerId"/>
                <input id="submitPurchase" type="submit" value="Submit" class="btn btn-primary"/>
                <div>
                    @Html.ActionLink("Cancel", "ViewListingsByEvent", "Listing", new { id = @Model.Listing.EventId}, new {@class="btn btn-default"})
                </div>
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('.purchaseForm').card({
            // a selector or jQuery object for the container
            // where you want the card to appear
            container: '.card-wrapper', // *required*
            numberInput: '.number', // optional — default input[name="number"]
            expiryInput: '.expiry', // optional — default input[name="expiry"]
            cvcInput: '.cvc', // optional — default input[name="cvc"]
            nameInput: '.name', // optional - defaults input[name="name"]
            formatting: true // optional - default true
        });
    </script>
 }

TicketTrader/Views/Transaction/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
<h3>Your tickets have been successfully purchased!</h3>
@Html.ActionLink("Return to home page", "Index", "Band")